environment:
  matrix:
    - NODEJS_VERSION: '4'
    - NODEJS_VERSION: '6'
    - NODEJS_VERSION: '8'
    - NODEJS_VERSION: '10'

install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - set PATH=%APPDATA%\npm;%PATH%
  - cmd: appveyor-retry npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test:appveyor

matrix:
  fast_finish: true

shallow_clone: true

build: off
deploy: off

cache:
  - '%APPDATA%\npm-cache'
